name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Override version'
        required: false
        default: ''
        type: string

permissions: {}

jobs:
  build-rust:
    runs-on: namespace-profile-linux-x64-default
    permissions:
      contents: read
    env:
      VERSION: ${{ inputs.version }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/actions/clone

      - uses: oxc-project/setup-rust@d286d43bc1f606abbd98096666ff8be68c8d5f57 # v1.0.2
        with:
          save-cache: false

      - uses: oxc-project/setup-node@fdbf0dfd334c4e6d56ceeb77d91c76339c2a0885 # v1.0.4

      - name: Build with upstream
        uses: ./.github/actions/build-upstream
        with:
          target: x86_64-unknown-linux-gnu
